# Permalinks
# permalink:           pretty

# Setup
title:               Fabiano Nunes
tagline:             '//[-]'
description:         ''
url:                 https://fabianonunes.github.io
baseurl:             ''
paginate:            5

author:
  name:              Fabiano Nunes
  url:               https://fabianonunes.github.io
  email:             '@fab_tc'

gems:                [jekyll-paginate]

# Custom vars
version:             1.0.0
